import rawPosts from './posts.json';

/**
 * Blog corpus, migrated from the previous WordPress install.
 *
 * `posts.json` is generated by `scripts/import-blog.py` and committed, so the
 * build never depends on the old CMS being reachable. Publish dates are the
 * originals — they feed `datePublished` in the BlogPosting schema and must not
 * be re-stamped on import.
 */

export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  publishedAt: string;
  updatedAt: string;
  categories: string[];
  tags: string[];
  /** Null for the two legacy posts that never had a featured image. */
  image: string | null;
  imageAlt: string;
  readingMinutes: number;
  /** Sanitised HTML — a whitelist of semantic tags, styled by `.prose-vanzoo`. */
  body: string;
};

/** Newest first, as produced by the importer. */
export const posts = rawPosts as Post[];

const bySlug = new Map(posts.map((post) => [post.slug, post]));

export function getPost(slug: string): Post | undefined {
  return bySlug.get(slug);
}

/** Placeholder used where a migrated post has no featured image of its own. */
export const FALLBACK_POST_IMAGE = '/images/garment-rail-couture.jpg';
export const FALLBACK_POST_IMAGE_ALT =
  'Couture garments on a rail at the Vanzoo eco-friendly dry cleaning atelier in Gurgaon';

export function postImage(post: Post) {
  return {
    src: post.image ?? FALLBACK_POST_IMAGE,
    alt: post.image ? post.imageAlt : FALLBACK_POST_IMAGE_ALT,
  };
}

/** Primary category — first is the one WordPress listed first. "Uncategorized"
 *  is never surfaced as a label, since it reads as a CMS artefact. */
export function primaryCategory(post: Post): string {
  return post.categories.find((c) => c !== 'Uncategorized') ?? 'Fabric Care';
}

export const categories: string[] = Array.from(
  new Set(posts.map(primaryCategory)),
).sort();

export function categorySlug(category: string): string {
  return category
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function categoryFromSlug(slug: string): string | undefined {
  return categories.find((category) => categorySlug(category) === slug);
}

export function postsInCategory(category: string): Post[] {
  return posts.filter((post) => primaryCategory(post) === category);
}

/**
 * Related posts for the article footer: same primary category first, topped up
 * with the most recent remaining posts so the slot is never short.
 */
export function relatedPosts(post: Post, count = 3): Post[] {
  const category = primaryCategory(post);
  const others = posts.filter((p) => p.slug !== post.slug);
  const sameCategory = others.filter((p) => primaryCategory(p) === category);
  const rest = others.filter((p) => primaryCategory(p) !== category);
  return [...sameCategory, ...rest].slice(0, count);
}

export function formatPostDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'Asia/Kolkata',
  });
}

/**
 * Splits an article body so a CTA can sit mid-flow (§3.10).
 *
 * The cut is taken at the last `</p>` before the halfway mark, so the banner
 * always lands between paragraphs rather than inside a list or a heading's
 * follow-on text. Short articles return no split — interrupting a three-minute
 * read would be worse than waiting for the CTA at the end.
 */
export function splitBodyForInlineCta(body: string): [string, string] | null {
  const boundaries: number[] = [];
  const pattern = /<\/p>/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(body)) !== null) {
    boundaries.push(match.index + match[0].length);
  }
  if (boundaries.length < 8) return null;

  const midpoint = body.length / 2;
  const cut = boundaries.filter((index) => index < midpoint).pop();
  if (!cut) return null;

  return [body.slice(0, cut), body.slice(cut)];
}

/** Legacy WordPress URLs were root-level (`/slug/`); the rebuild namespaces
 *  them under `/blogs/`. Consumed by the redirect map in next.config.mjs. */
export const legacyPostRedirects = posts.map((post) => ({
  source: `/${post.slug}`,
  destination: `/blogs/${post.slug}/`,
}));
