import rawPolicies from './policies.json';

/**
 * Policy documents, migrated verbatim from vanzoo.in.
 *
 * Generated by `scripts/import-policies.py`; section headings are promoted to
 * `h2` with stable ids so the sticky table of contents can link into them.
 */

export type PolicyDoc = {
  slug: string;
  /** Original `<title>` from the live site, reused so search results don't shift. */
  title: string;
  description: string;
  heading: string;
  route: string;
  toc: { id: string; label: string }[];
  body: string;
};

const map = rawPolicies as Record<string, Omit<PolicyDoc, 'slug'>>;

export const policies: PolicyDoc[] = Object.entries(map).map(([slug, doc]) => ({
  slug,
  ...doc,
}));

export function getPolicy(slug: string): PolicyDoc | undefined {
  return policies.find((doc) => doc.slug === slug);
}

/**
 * Vanzoo does not publish an effective date on any policy page. Rather than
 * invent one, we surface the date this content was migrated — accurate, and
 * still useful to a reader deciding whether they've seen the current version.
 */
export const POLICY_LAST_UPDATED = '2026-08-06';
